# Generated by Django 4.1.7 on 2023-03-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created',
        ),
    ]
