# Generated by Django 4.1.7 on 2023-04-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_comment_options_comment_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='descriptions',
            new_name='about',
        ),
    ]
