# Generated by Django 4.1.7 on 2023-04-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_descriptions_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
