# Generated by Django 4.1.7 on 2023-04-10 06:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
